# Makefile for my GLES-based library: Glesly
#

NAME                 =  Glesly_Base
VERS_MAJOR           =  0
VERS_MINOR           =  1

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

BASE_LIBRARIES       =  pangocairo

include $(SCRIPTDIR)/makelib

